src/Entity/BatchImport.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BatchImportRepository")
 */
class BatchImport
{
    const TYPE_RCR_CREA = 1;
    const TYPE_UNICA = 2;

    const STATUS_NEW = 0;
    const STATUS_RUNNING = 1;
    const STATUS_FINISHED = 2;
    const STATUS_ERROR = 3;
    const STATUS_CANCEL = 4;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Rcr", inversedBy="batchImports")
     * @ORM\JoinColumn(nullable=false)
     */
    private $rcr;

    /**
     * @ORM\Column(type="smallint")
     */
    private $type;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Record", mappedBy="batchImport")
     */
    private $records;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $countRecords;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $countErrors;

    /**
     * @ORM\Column(type="smallint")
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $startDate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    public function __construct(Rcr $rcr = null, int $type = null)
    {
        $this->records = new ArrayCollection();
        $this->setRcr($rcr);
        $this->setType($type);
        $this->setStartDate(new DateTime());
        $this->setCountRecords(0);
        $this->setCountErrors(0);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRcr(): ?Rcr
    {
        return $this->rcr;
    }

    public function setRcr(?Rcr $rcr): self
    {
        $this->rcr = $rcr;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function getTypeLabel(): string
    {
        switch ($this->getType()) {
            case self::TYPE_RCR_CREA:
                return "RCR CRÉATEUR";
            case self::TYPE_UNICA:
                return "UNICA";
        }
        return "";
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection|Record[]
     */
    public function getRecords(): Collection
    {
        return $this->records;
    }

    public function addRecord(Record $record): self
    {
        if (!$this->records->contains($record)) {
            $this->records[] = $record;
            $record->setBatchImport($this);
        }

        return $this;
    }

    public function removeRecord(Record $record): self
    {
        if ($this->records->contains($record)) {
            $this->records->removeElement($record);
            // set the owning side to null (unless already changed)
            if ($record->getBatchImport() === $this) {
                $record->setBatchImport(null);
            }
        }

        return $this;
    }

    public function getRecordsByStatus() {
        $stats = [];
        foreach ($this->getRecords() as $record) {
            if (!isset($stats[$record->getStatus()])) {
                $stats[$record->getStatus()] = 1;
            } else {
                $stats[$record->getStatus()] += 1;
            }
        }

        $output = [];
        foreach ($stats as $status => $count) {
            $statusLabel = null;
            switch ($status) {
                case Record::RECORD_TODO:
                    $statusLabel = "Notices à corriger";
                    break;
                case Record::RECORD_VALIDATED:
                    $statusLabel = "Notices corrigées";
                    break;

                case Record::RECORD_SKIPPED:
                    $statusLabel = "Notices laissées de côté";
                    break;

                case Record::RECORD_FIXED_OUTSIDE:
                    $statusLabel = "Notices corrigées hors algoliens";
                    break;
            }

            $output[$status] = ["label" => $statusLabel, "count" => $count];
        }

        return $output;
    }

    public function getCountRecords(): ?int
    {
        return $this->countRecords;
    }

    public function setCountRecords(int $countRecords): self
    {
        $this->countRecords = $countRecords;

        return $this;
    }

    public function getCountErrors(): ?int
    {
        return $this->countErrors;
    }

    public function setCountErrors(int $countErrors): self
    {
        $this->countErrors = $countErrors;

        return $this;
    }

    public function updateCountErrors(): void
    {
        /** @var Record $record */
        $count = 0;
        foreach ($this->getRecords() as $record) {
            $count += sizeof($record->getLinkErrors());
        }
        $this->setCountErrors($count);
    }

    public function getDurationAsString(): string
    {
        return $this->getDuration()->format("%Imin %ss %F");
    }

    public function getDuration()
    {
        return $this->getStartDate()->diff($this->getEndDate());
    }

    public function getStartedSince()
    {
        if (is_null($this->getStartDate())) {
            return null;
        }
        return $this->getStartDate()->diff(new DateTime())->format("%Imin %ss");
    }

    public function getIlnCode(): string
    {
        return $this->getRcr()->getIln()->getCode();
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function getStatusLabel(): string
    {
        switch ($this->status) {
            case BatchImport::STATUS_CANCEL:
                return "Annulé";
            case BatchImport::STATUS_FINISHED:
                return "Terminé";
            case BatchImport::STATUS_ERROR:
                return "Erreur";
            case BatchImport::STATUS_RUNNING:
                return "En cours";
        }
        return $this->status;
    }

    public function getStatusClass(): string
    {
        switch ($this->status) {
            case BatchImport::STATUS_CANCEL:
                return "danger";
            case BatchImport::STATUS_FINISHED:
                return "success";
            case BatchImport::STATUS_ERROR:
                return "warning";
            case BatchImport::STATUS_RUNNING:
                return "warning";
        }
        return "";
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getEndDate(): ?DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(?DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getStartDate(): ?DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(?DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }
}

src/Entity/Rcr.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RcrRepository")
 */
class Rcr
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=9)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Iln", inversedBy="rcrs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $iln;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Record", mappedBy="rcrCreate")
     */
    private $records;

    /**
     * @ORM\Column(type="smallint")
     */
    private $harvested;

    /**
     * @ORM\Column(type="boolean", options={"default": 1})
     */
    private $active;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BatchImport", mappedBy="rcr")
     */
    private $batchImports;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $recordsStatus0;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $recordsStatus1;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $recordsStatus2;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $recordsStatus3;

    public function __construct()
    {
        $this->records = new ArrayCollection();
        $this->batchImports = new ArrayCollection();

        $this->recordsStatus0 = 0;
        $this->recordsStatus1 = 0;
        $this->recordsStatus2 = 0;
        $this->recordsStatus3 = 0;
    }

    public function __toString()
    {
        return $this->getLabel();
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getUpdated(): ?DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    public function getIln(): ?Iln
    {
        return $this->iln;
    }

    public function setIln(?Iln $iln): self
    {
        $this->iln = $iln;

        return $this;
    }

    /**
     * @return Collection|Record[]
     */
    public function getRecords(): Collection
    {
        return $this->records;
    }

    public function addRecord(Record $record): self
    {
        if (!$this->records->contains($record)) {
            $this->records[] = $record;
            $record->setRcrCreate($this);
        }

        return $this;
    }

    public function removeRecord(Record $record): self
    {
        if ($this->records->contains($record)) {
            $this->records->removeElement($record);
            // set the owning side to null (unless already changed)
            if ($record->getRcrCreate() === $this) {
                $record->setRcrCreate(null);
            }
        }

        return $this;
    }

    public function getNumberOfRecords(): ?int
    {
        return $this->getRecordsStatus0() + $this->getRecordsStatus1() + $this->getRecordsStatus2() + $this->getRecordsStatus3();
    }

    public function getNumberOfRecordsCorrected(): ?int
    {
        return $this->getCountRecordsByStatus(Record::RECORD_VALIDATED);
    }


    public function getRecordsStatus0(): ?int
    {
        return $this->recordsStatus0;
    }

    public function setRecordsStatus0(int $recordsStatus0): self
    {
        $this->recordsStatus0 = $recordsStatus0;

        return $this;
    }

    public function getRecordsStatus1(): ?int
    {
        return $this->recordsStatus1;
    }

    public function setRecordsStatus1(int $recordsStatus1): self
    {
        $this->recordsStatus1 = $recordsStatus1;

        return $this;
    }

    public function getRecordsStatus2(): ?int
    {
        return $this->recordsStatus2;
    }

    public function setRecordsStatus2(int $recordsStatus2): self
    {
        $this->recordsStatus2 = $recordsStatus2;

        return $this;
    }

    public function getRecordsStatus3(): ?int
    {
        return $this->recordsStatus3;
    }

    public function setRecordsStatus3(int $recordsStatus3): self
    {
        $this->recordsStatus3 = $recordsStatus3;

        return $this;
    }

    public function getNumberOfRecordsAvailable(): int
    {
        return $this->getCountRecordsByStatus(Record::RECORD_TODO);
    }

    public function getCountRecordsByStatus(int $status)
    {
        switch ($status) {
            case Record::RECORD_TODO:
                return $this->getRecordsStatus0();
            case Record::RECORD_VALIDATED:
                return $this->getRecordsStatus1();
            case Record::RECORD_SKIPPED:
                return $this->getRecordsStatus2();
            case Record::RECORD_FIXED_OUTSIDE:
                return $this->getRecordsStatus3();
        }
        return 0;
    }

    public function getNumberOfRecordsReprise(): int
    {
        return $this->getCountRecordsByStatus(Record::RECORD_SKIPPED);
    }

    public function getNumberOfRecordsFixedOutside(): int
    {
        return $this->getCountRecordsByStatus(Record::RECORD_FIXED_OUTSIDE);
    }

    public function setNumberOfRecordsCorrected(int $value): void
    {
        $this->setCountRecordsByStatus(Record::RECORD_VALIDATED, $value);
    }

    public function setNumberOfRecordsReprise(int $value): void
    {
        $this->setCountRecordsByStatus(Record::RECORD_SKIPPED, $value);
    }

    public function setCountRecordsByStatus(int $status, int $value): void
    {
        switch ($status) {
            case Record::RECORD_TODO:
                $this->setRecordsStatus0($value);
                return;
            case Record::RECORD_VALIDATED:
                $this->setRecordsStatus1($value);
                return;
            case Record::RECORD_SKIPPED:
                $this->setRecordsStatus2($value);
                return;
            case Record::RECORD_FIXED_OUTSIDE:
                $this->setRecordsStatus3($value);
                return;
        }
    }

    public function getHarvested(): ?int
    {
        return $this->harvested;
    }

    public function setHarvested(int $harvested): self
    {
        $this->harvested = $harvested;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function addBatchImport(BatchImport $batchImport): self
    {
        if (!$this->batchImports->contains($batchImport)) {
            $this->batchImports[] = $batchImport;
            $batchImport->setRcr($this);
        }

        return $this;
    }

    public function hasBatchRun(int $batchType)
    {
        foreach ($this->getBatchImports() as $batchImport) {
            if ($batchImport->getType() == $batchType) {
                return $batchImport;
            }
        }
        return false;
    }

    /**
     * @return Collection|BatchImport[]
     */
    public function getBatchImports(): Collection
    {
        return $this->batchImports;
    }

    public function removeBatchImport(BatchImport $batchImport): self
    {
        if ($this->batchImports->contains($batchImport)) {
            $this->batchImports->removeElement($batchImport);
            // set the owning side to null (unless already changed)
            if ($batchImport->getRcr() === $this) {
                $batchImport->setRcr(null);
            }
        }

        return $this;
    }
}

templates/record/_record.html.twig
<div class="row">
    <div class="col-12">
        <h2 id="record_title">
            Notice {{ record.ppn }}{% if record.title != '' %} - {{ record.title }} ({{ record.year }}){% endif %}</h2>
        <div id="unloca"></div>
        {% if record.status != constant("App\\Entity\\Record::RECORD_TODO") %}
            <div class="alert alert-warning">
                Cette notice a déjà le statut <strong>
                    {% if record.status == constant("App\\Entity\\Record::RECORD_VALIDATED") %}
                        corrigé
                    {% elseif record.status == constant("App\\Entity\\Record::RECORD_SKIPPED") %}
                        à reprendre document en main
                        {% if record.skipReason is defined %}
                            ({{ record.skipReason }})
                        {% endif %}
                    {% endif %}</strong>
                <br/>
                <i>{{ record.comment }}</i>
            </div>
        {% elseif record.comment != "" %}
            <div class="alert alert-warning">
                Cette notice a déjà été proposé à un·e collègue qui l'a passée avec le commentaire suivant :
                <br/>
                <i>{{ record.comment }}</i>
            </div>
        {% endif %}

        <p>Information sur le document : <span class="badge badge-info">{{ record.docTypeLabel }}</span>
            {% if record.batchImport %}<span
                    class="badge badge-primary">{{ record.batchImport.typeLabel }}</span>{% endif %}
        </p>

        <a href="#" id="btn_unimarc" class="btn btn-info">Afficher la notice unimarc</a>
        <div id="sudoc_record" class="collapse">
            {% if record.marcBefore != "" %}
                <pre>{{ record.marcBefore }}</pre>
            {% else %}
                <div class="lds-ellipsis">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            {% endif %}
        </div>

        <br/>
        <a href="#" data-qualimarc-url="{{ url("ajax_get_qualimarc", {ppn: record.ppn}) }}" data-ppn="{{ record.ppn }}" id="btn_qualimarc" class="btn btn-info">Afficher l'analyse Qualimarc</a>
        <div id="qualimarc_result" class="collapse">
            <img src="{{ asset("img/loader.gif") }}" alt="Chargement en cours"/>
        </div>


        {% if record.status != constant("App\\Entity\\Record::RECORD_VALIDATED") %}
            <hr/>
            <h2>Analyse algoliens</h2>
            <p>
                La notice n°<a target="_blank" href="http://www.sudoc.fr/{{ record.ppn }}">{{ record.ppn }}</a> vous
                est proposée car
                {% if record.batchImport %}
                    {% if record.batchImport.typeLabel == "UNICA" %}
                        le RCR {{ record.rcrCreate.code }} est le seul établissement du réseau localisé dessus  et qu'
                    {% else %}
                        le RCR {{ record.rcrCreate.code }} en est le créateur et qu'
                    {% endif %}
                {% endif %}
                elle comporte les erreurs suivantes :</p>
            <ul>
                {% for linkError in record.linkErrors %}
                    <li><strong>{{ linkError.errorCode }}</strong> : au moins {{ linkError.errorText }};</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
</div>
{% if record.status != constant("App\\Entity\\Record::RECORD_VALIDATED") %}
    <div class="row">
        <div class="col-12">
            <h2>Actions suggérées</h2>

            {% if app.session.get("winnie") %}
                <p>Corriger la notice sur WinIBW</p>
            {% endif %}
            {% set countLinks = 0 %}
            {% for linkError in record.linkErrors %}
            {% if linkError.paprikaLinks|length > 0 %}
            {% for paprikaLink in linkError.paprikaLinks %}
            {% if countLinks == 0 %}
            {% set countLinks = 1 %}
            {% if app.session.get("winnie") %}
                <strong>OU</strong><br/>
            {% endif %}
            Corriger les liens suivants à l'aide de Paprika :
            <ul>


                {% endif %}

                <li>{{ paprikaLink.label }} &rarr; <a target="_blank" href="{{ paprikaLink.url }}">voir sur
                        Paprika</a></li>

                {% endfor %}
                {% endif %}
                {% endfor %}
                {% if countLinks == 1 %}
            </ul>
            {% endif %}
            <p>Si vous ne souhaitez pas corriger cette notice maintenant mais souhaitez qu'elle soit à nouveau
                proposée plus tard dans le cadre de chantier, vous pouvez la laisser de côté pour le moment :
                <br/><a href="{% if permalink is defined %}
            {{ url("view_record_rcr", {'ilnCode': iln.code, 'ilnSecret': iln.secret, 'rcrCode': rcr.code}) }}
{% else %}
{{ app.request.uri }}
{% endif %}" class="btn btn-outline-primary">Voir une autre notice</a>
            <p><small>Si vous pensez que cette notice pourra être traitée directement par un collègue, envoyez-lui ce
                    lien
                    direct avant de passer à une autre notice (clic-droit > copier l'adresse du lien) : <a
                            href="{{ url("view_record_permalink", {ilnCode: iln.code, ilnSecret: iln.secret, rcrCode: rcr.code, idRecord: record.id, ppn: record.ppn}) }}">{{ url("view_record_permalink", {ilnCode: iln.code, ilnSecret: iln.secret, rcrCode: rcr.code, idRecord: record.id, ppn: record.ppn}) }}</a></small>
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <h2>Enregistrer</h2>
        </div>
    </div>
    {{ form_start(form) }}
    <div class="row">
        <div class="col-6 text-right">
            <h3>Option 1 : notice corrigée</h3>
            <p>La notice a été corrigée dans WinIBW ou Paprika, ne plus la proposer aux collègues.</p>
            {{ form_widget(form.validate) }}
        </div>
        <div class="col-6 text-left" style="border-left:2px solid grey">
            <h3>Option 2 : notice non traitée</h3>

            {% if form.skipReason is defined %}
                {{ form_row(form.skipReason) }}
            {% else %}
                <p>Cette notice n'a pas pu être traitée pour le moment. À reprendre document en main.</p>
            {% endif %}
            {{ form_row(form.comment) }}
            {{ form_widget(form.skip) }}
        </div>
    </div>
    {{ form_end(form) }}
{% endif %}

templates/record/record_for_lang.html.twig
{% extends "record/record_view.html.twig" %}

templates/record/record_for_rcr.html.twig
{% extends "record/record_view.html.twig" %}

templates/record/record_view.html.twig
{% extends "includes/base.html.twig" %}
{% block javascripts %}
    {% if record is not null %}
        <script type="text/javascript">
            var url_raw_record = "{{ url("raw_record", {'ppn': record.ppn}) }}";
            var record_has_marc = false;
            {% if record.marcBefore != "" %}
            record_has_marc = true;
            {% endif %}

            var url_is_localized = "";
            {% if record.batchImport is not null %}
            {% if record.batchImport.typeLabel == "RCR CRÉATEUR" %}
            var url_is_localized = "{{ url("verif_loca", {'ppn': record.ppn, 'rcr': rcr.code}) }}";
            {% endif %}
            {% endif %}
        </script>

        {{ encore_entry_script_tags('record_view') }}
    {% endif %}
    <!-- Renders app.js & a webpack runtime.js file
        <script src="/build/runtime.js"></script>
        <script src="/build/app.js"></script> -->
{% endblock %}

{% block body %}
    {{ include("includes/_breadcrumb.html.twig", {'page': 'record'}) }}

    {% if record is null %}
        <div>
            <p><strong>Plus aucune notice à traiter pour ce RCR !</strong></p>
            {% if not app.session.get("winnie") %}
                {% if rcr.numberOfRecordsAvailable %}
                    <p>Il reste {{ rcr.numberOfRecordsAvailable }} marquées comme à traiter pour ce RCR mais elles
                        contiennent des erreurs qui nécessitent WinIBW qui ne semble pas installé sur votre poste (<a
                                href="{{ url("settings", {code: iln.code, secret: iln.secret}) }}">modifier ce
                            paramètre</a>)</p>
                {% endif %}
            {% endif %}

            {% if lockedRecords|length > 0 %}
                <div class="alert alert-warning">
                    <p>
                        {{ lockedRecords|length }} notices sont marquées comme à traiter dans la base mais sont
                        "bloquées" car affichées dans cette interface il y a moins d'une heure. Le blocage des ces
                        notices est destinée à éviter qu'une notice ne soit présentée simultanément à deux utilisateurs
                        qui tenteraient alors de la modifier.
                    </p>
                    <p>
                        Les notices concernées sont :
                    <ul>
                        {% for record in lockedRecords %}
                            <li><a href="https://www.sudoc.fr/{{ record.ppn }}" target="_blank">{{ record.ppn }}</a>
                                : {{ record.title }} ({{ record.year }})
                            </li>
                        {% endfor %}
                    </ul>
                    </p>
                    <p>
                        Si vous le souhaitez, vous pouvez <a
                                href="{{ url("force_unlock", {ilnCode: iln.code, rcrCode: rcr.code, ilnSecret: iln.secret}) }}"
                                class="btn btn-info">forcer le déblocage</a> de ces notices.
                    </p>
                </div>
            {% endif %}
            Peut-être un <a href="{{ url('view_iln', {'code': iln.code, 'secret': iln.secret}) }}">autre RCR de cet
                ILN</a> ?
        </div>
    {% else %}
        {% include "record/_record.html.twig" %}
    {% endif %}
{% endblock %}