src/Entity/Iln.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\IlnRepository")
 */
class Iln
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=12)
     */
    private $code;

    /**
     * @ORM\Column(type="integer")
     */
    private $number;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Rcr", mappedBy="iln")
     */
    private $rcrs;

    /**
     * @ORM\Column(type="string", length=4)
     */
    private $secret;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\SkipReason", mappedBy="Iln")
     */
    private $skipReasons;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $hasLanguages;

    public function __construct()
    {
        $this->rcrs = new ArrayCollection();
        $this->skipReasons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    /**
     * @return Collection|Rcr[]
     */
    public function getRcrsWithRecords(): Collection
    {
        $output = $this->rcrs->filter(function ($rcr) {
            return (($rcr->getActive() == 1) and ($rcr->getNumberOfRecords() > 0));
        });
        return $output;
    }

    /**
     * @return Collection|Rcr[]
     */
    public function getRcrsWithRecordsFixedOutside(): Collection
    {
        $output = $this->rcrs->filter(function (Rcr $rcr) {
            return (($rcr->getActive() == 1) and ($rcr->getNumberOfRecordsFixedOutside() > 0));
        });
        return $output;
    }

    public function addRcr(Rcr $rcr): self
    {
        if (!$this->rcrs->contains($rcr)) {
            $this->rcrs[] = $rcr;
            $rcr->setIln($this);
        }

        return $this;
    }

    public function removeRcr(Rcr $rcr): self
    {
        if ($this->rcrs->contains($rcr)) {
            $this->rcrs->removeElement($rcr);
            // set the owning side to null (unless already changed)
            if ($rcr->getIln() === $this) {
                $rcr->setIln(null);
            }
        }

        return $this;
    }

    public function getNumberOfRecords()
    {
        return array_reduce($this->getRcrs()->getValues(), function ($total, $rcr) {
            $total += $rcr->getNumberOfRecords();
            return $total;
        });
    }

    /**
     * @return Collection|Rcr[]
     */
    public function getRcrs(): Collection
    {
        $output = $this->rcrs->filter(function ($rcr) {
            return $rcr->getActive() == 1;
        });
        return $output;
    }

    public function getNumberOfRecordsCorrected()
    {
        return array_reduce($this->getRcrs()->getValues(), function ($total, Rcr $rcr) {
            $total += $rcr->getCountRecordsByStatus(record::RECORD_VALIDATED);
            return $total;
        });
    }

    public function getNumberOfRecordsHandled()
    {
        return array_reduce($this->getRcrs()->getValues(), function ($total, Rcr $rcr) {
            $total += $rcr->getCountRecordsByStatus(Record::RECORD_SKIPPED) + $rcr->getCountRecordsByStatus(Record::RECORD_VALIDATED);
            return $total;
        });
    }

    public function getNumberOfRecordsReprise()
    {
        return array_reduce($this->getRcrs()->getValues(), function ($total, $rcr) {
            $total += $rcr->getNumberOfRecordsReprise();
            return $total;
        });
    }

    public function getSecret(): ?string
    {
        return $this->secret;
    }

    public function setSecret(string $secret): self
    {
        $this->secret = $secret;

        return $this;
    }

    public function getDefaultSkipReason()
    {
        return $this->skipReasons[0];
    }

    /**
     * @return Collection|SkipReason[]
     */
    public function getSkipReasons(): Collection
    {
        return $this->skipReasons;
    }

    public function addSkipReason(SkipReason $skipReason): self
    {
        if (!$this->skipReasons->contains($skipReason)) {
            $this->skipReasons[] = $skipReason;
            $skipReason->setIln($this);
        }

        return $this;
    }

    public function removeSkipReason(SkipReason $skipReason): self
    {
        if ($this->skipReasons->contains($skipReason)) {
            $this->skipReasons->removeElement($skipReason);
            // set the owning side to null (unless already changed)
            if ($skipReason->getIln() === $this) {
                $skipReason->setIln(null);
            }
        }

        return $this;
    }

    public function getHasLanguages(): ?bool
    {
        return $this->hasLanguages;
    }

    public function setHasLanguages(bool $hasLanguages): self
    {
        $this->hasLanguages = $hasLanguages;

        return $this;
    }

}

src/Entity/Rcr.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RcrRepository")
 */
class Rcr
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=9)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Iln", inversedBy="rcrs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $iln;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Record", mappedBy="rcrCreate")
     */
    private $records;

    /**
     * @ORM\Column(type="smallint")
     */
    private $harvested;

    /**
     * @ORM\Column(type="boolean", options={"default": 1})
     */
    private $active;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BatchImport", mappedBy="rcr")
     */
    private $batchImports;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $recordsStatus0;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $recordsStatus1;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $recordsStatus2;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $recordsStatus3;

    public function __construct()
    {
        $this->records = new ArrayCollection();
        $this->batchImports = new ArrayCollection();

        $this->recordsStatus0 = 0;
        $this->recordsStatus1 = 0;
        $this->recordsStatus2 = 0;
        $this->recordsStatus3 = 0;
    }

    public function __toString()
    {
        return $this->getLabel();
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getUpdated(): ?DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    public function getIln(): ?Iln
    {
        return $this->iln;
    }

    public function setIln(?Iln $iln): self
    {
        $this->iln = $iln;

        return $this;
    }

    /**
     * @return Collection|Record[]
     */
    public function getRecords(): Collection
    {
        return $this->records;
    }

    public function addRecord(Record $record): self
    {
        if (!$this->records->contains($record)) {
            $this->records[] = $record;
            $record->setRcrCreate($this);
        }

        return $this;
    }

    public function removeRecord(Record $record): self
    {
        if ($this->records->contains($record)) {
            $this->records->removeElement($record);
            // set the owning side to null (unless already changed)
            if ($record->getRcrCreate() === $this) {
                $record->setRcrCreate(null);
            }
        }

        return $this;
    }

    public function getNumberOfRecords(): ?int
    {
        return $this->getRecordsStatus0() + $this->getRecordsStatus1() + $this->getRecordsStatus2() + $this->getRecordsStatus3();
    }

    public function getNumberOfRecordsCorrected(): ?int
    {
        return $this->getCountRecordsByStatus(Record::RECORD_VALIDATED);
    }


    public function getRecordsStatus0(): ?int
    {
        return $this->recordsStatus0;
    }

    public function setRecordsStatus0(int $recordsStatus0): self
    {
        $this->recordsStatus0 = $recordsStatus0;

        return $this;
    }

    public function getRecordsStatus1(): ?int
    {
        return $this->recordsStatus1;
    }

    public function setRecordsStatus1(int $recordsStatus1): self
    {
        $this->recordsStatus1 = $recordsStatus1;

        return $this;
    }

    public function getRecordsStatus2(): ?int
    {
        return $this->recordsStatus2;
    }

    public function setRecordsStatus2(int $recordsStatus2): self
    {
        $this->recordsStatus2 = $recordsStatus2;

        return $this;
    }

    public function getRecordsStatus3(): ?int
    {
        return $this->recordsStatus3;
    }

    public function setRecordsStatus3(int $recordsStatus3): self
    {
        $this->recordsStatus3 = $recordsStatus3;

        return $this;
    }

    public function getNumberOfRecordsAvailable(): int
    {
        return $this->getCountRecordsByStatus(Record::RECORD_TODO);
    }

    public function getCountRecordsByStatus(int $status)
    {
        switch ($status) {
            case Record::RECORD_TODO:
                return $this->getRecordsStatus0();
            case Record::RECORD_VALIDATED:
                return $this->getRecordsStatus1();
            case Record::RECORD_SKIPPED:
                return $this->getRecordsStatus2();
            case Record::RECORD_FIXED_OUTSIDE:
                return $this->getRecordsStatus3();
        }
        return 0;
    }

    public function getNumberOfRecordsReprise(): int
    {
        return $this->getCountRecordsByStatus(Record::RECORD_SKIPPED);
    }

    public function getNumberOfRecordsFixedOutside(): int
    {
        return $this->getCountRecordsByStatus(Record::RECORD_FIXED_OUTSIDE);
    }

    public function setNumberOfRecordsCorrected(int $value): void
    {
        $this->setCountRecordsByStatus(Record::RECORD_VALIDATED, $value);
    }

    public function setNumberOfRecordsReprise(int $value): void
    {
        $this->setCountRecordsByStatus(Record::RECORD_SKIPPED, $value);
    }

    public function setCountRecordsByStatus(int $status, int $value): void
    {
        switch ($status) {
            case Record::RECORD_TODO:
                $this->setRecordsStatus0($value);
                return;
            case Record::RECORD_VALIDATED:
                $this->setRecordsStatus1($value);
                return;
            case Record::RECORD_SKIPPED:
                $this->setRecordsStatus2($value);
                return;
            case Record::RECORD_FIXED_OUTSIDE:
                $this->setRecordsStatus3($value);
                return;
        }
    }

    public function getHarvested(): ?int
    {
        return $this->harvested;
    }

    public function setHarvested(int $harvested): self
    {
        $this->harvested = $harvested;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function addBatchImport(BatchImport $batchImport): self
    {
        if (!$this->batchImports->contains($batchImport)) {
            $this->batchImports[] = $batchImport;
            $batchImport->setRcr($this);
        }

        return $this;
    }

    public function hasBatchRun(int $batchType)
    {
        foreach ($this->getBatchImports() as $batchImport) {
            if ($batchImport->getType() == $batchType) {
                return $batchImport;
            }
        }
        return false;
    }

    /**
     * @return Collection|BatchImport[]
     */
    public function getBatchImports(): Collection
    {
        return $this->batchImports;
    }

    public function removeBatchImport(BatchImport $batchImport): self
    {
        if ($this->batchImports->contains($batchImport)) {
            $this->batchImports->removeElement($batchImport);
            // set the owning side to null (unless already changed)
            if ($batchImport->getRcr() === $this) {
                $batchImport->setRcr(null);
            }
        }

        return $this;
    }
}

templates/iln/iln.html.twig
{% extends "includes/base.html.twig" %}
{% block header %}
{% endblock %}

{% block body %}
    {{ include("includes/_breadcrumb.html.twig", {'page': 'iln'}) }}
    <div class="alert alert-secondary">
        <p>En choisissant un RCR ci-dessous, une notice créée par ce RCR et qui a un problème de lien vous sera
            proposée.</p>
        <p> Vous pouvez alors :</p>
        <ul>
            <li>faire les corrections nécessaires via Winibw ou Paprika → cette notice ne sera plus proposée</li>
            <li>passer votre tour → cette notice pourra être proposée à nouveau à l'avenir</li>
        </ul>
        <p>
            {{ iln.getNumberOfRecordsHandled }} notices traitées jusqu'ici pour cet ILN (<a
                    href="{{ url("view_iln_stats", {'code': iln.code, 'secret': iln.secret}) }}">détail</a>).
        </p>
    </div>
    <h1>Accès par PPN</h1>
    <p>Si pour une raison quelconque vous avez besoin de retrouver la fiche correspond à une notice particulière,
        saisissez le ci-dessous : </p>
    {{ render(controller(
        'App\\Controller\\IlnController::searchPpn', {'code': iln.code, 'secret': iln.secret}
    )) }}

    {% if iln.hasLanguages %}
        <h1>Accès par langue</h1>
        <p>Voir la <a href="{{ url("view_iln_langs", {code: iln.code, secret: iln.secret}) }}">page dédiée</a>.</p>
    {% endif %}
    <h1>Accès par RCR</h1>
    <table class="table">
        <tr>
            <th>RCR</th>
            <th>Libellé</th>
            <th>Reste à traiter</th>
            <th>À reprendre document en main</th>
        </tr>
        {% for rcr in iln.getRcrsWithRecords() %}
            <tr>
                <td>{{ rcr.code }}</td>
                <td>{{ rcr.label }}</td>
                <td>
                    <strong><a href="{{ url('view_record_rcr', {ilnCode: iln.code, rcrCode: rcr.code, ilnSecret: iln.secret}) }}">{{ rcr.numberOfRecordsAvailable }}</a></strong>
                </td>
                <td>
                    {% if rcr.numberOfRecordsReprise != 0 %}
                        <a href="{{ url("view_rcr_reprise", {ilnCode: iln.code, rcrCode: rcr.code, ilnSecret: iln.secret}) }}">{{ rcr.numberOfRecordsReprise }}</a>
                    {% else %}
                        -
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/iln/iln_stats.html.twig
{% extends "includes/base.html.twig" %}
{% block header %}
{% endblock %}

{% block body %}
    {{ include("includes/_breadcrumb.html.twig", {'page': 'stat'}) }}

    {% if iln.skipReasons | length > 0 %}
        <h1>Reprises à venir (<a href="{{ url("view_iln_reprises", {code: iln.code, secret: iln.secret}) }}">voir le
                détail</a>)</h1>
        <ul>
            {% for skipReason in iln.skipReasons %}
                <li>{{ skipReason.description }} : {{ skipReason.records|length }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <h1>Corrections hors algoliens</h1>
    <p>Depuis les premiers imports de notices dans cette interface pour {{ iln.label }}, des notices ont été corrigées
        sans être marquées comme corrigées dans cette interface et n'apparaissent plus ici. S'il ne nous est pas
        possible d'identifier les dates de correction de ces notices nous savons qu'elles ont disparues d'Algoliens et
        sont donc considérées comme corrigées (ces chiffres ne sont pas mis à jour en temps réel) : </p>
    <ul>
        {% for rcr in iln.rcrsWithRecordsFixedOutside %}
            <li>{{ rcr.label }} : {{ rcr.getNumberOfRecordsFixedOutside }}</li>
        {% endfor %}
    </ul>
    <h1>Historique (Exporter au format <a
                href="{{ url("export_iln_stats", {"code": iln.code, "secret": iln.secret, "format": "xlsx"}) }}">xlsx</a>,
        <a href="{{ url("export_iln_stats", {"code": iln.code, "secret": iln.secret, "format": "ods"}) }}">ods</a>, <a
                href="{{ url("export_iln_stats", {"code": iln.code, "secret": iln.secret, "format": "csv"}) }}">csv</a>)
    </h1>
    {% for year, yeardetail in stats %}
        {% set correctedrecords = 0 %}
        {% set correctederrors= 0 %}
        {% set repriserecords = 0 %}
        {% set repriseerrors = 0 %}
        <h3>{{ year }}</h3>
        <table class="table">
            <tr>
                <th rowspan="2">Jour</th>
                <th colspan="2">Corrections</th>
                <th colspan="2">Notices à reprendre document en main</th>
                <th colspan="2">Total</th>
            </tr>
            <tr>
                <th>Notices</th>
                <th>Liens</th>
                <th>Notices</th>
                <th>Liens</th>
                <th>Notices</th>
                <th>Liens</th>
            </tr>

            {% for month, monthdetail in yeardetail %}
                {% for day, daydetail in monthdetail %}
                    {% set correctedrecords = correctedrecords + daydetail["1"]["nbrecords"] %}
                    {% set correctederrors = correctederrors + daydetail["1"]["nberrors"] %}
                    {% set repriserecords = repriserecords + daydetail["2"]["nbrecords"] %}
                    {% set repriseerrors = repriseerrors + daydetail["2"]["nberrors"] %}
                    <tr>
                        <td>{{ day }}/{{ month }}</td>
                        <td>{{ daydetail["1"]["nbrecords"] }}</td>
                        <td>{{ daydetail["1"]["nberrors"] }}</td>
                        <td>{{ daydetail["2"]["nbrecords"] }}</td>
                        <td>{{ daydetail["2"]["nberrors"] }}</td>
                        <th>{{ daydetail["1"]["nbrecords"]  + daydetail["2"]["nbrecords"] }}</th>
                        <th>{{ daydetail["1"]["nberrors"]  + daydetail["2"]["nberrors"] }}</th>
                    </tr>
                {% endfor %}
            {% endfor %}
            <tr>
                <th>Total</th>
                <th>{{ correctedrecords }}</th>
                <th>{{ correctederrors }}</th>
                <th>{{ repriserecords }}</th>
                <th>{{ repriseerrors }}</th>
                <th>{{ correctedrecords + repriserecords }}</th>
            </tr>
        </table>
    {% endfor %}

    <h1>Information sur les chargements de notices</h1>
    <ul>
        {% for rcr in iln.rcrs %}
            <li>{{ rcr.code }} - {{ rcr.label }}
                {% if rcr.batchImports|length == 0 %}
                    : <i>aucun chargement</i>
                {% else %}
                    <ul>
                        {% for batch in rcr.batchImports %}
                            <li>{{ batch.typeLabel }} : {{ batch.startDate.format("d-m-Y à h:i:s") }} - <a
                                        href="{{ url("export_batch_import", {'code': iln.code, 'secret': iln.secret, 'id': batch.id}) }}">export
                                    les PPN des {{ batch.countRecords }} notices</a></li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/iln/langs.html.twig
{% extends "includes/base.html.twig" %}
{% block header %}
{% endblock %}

{% block body %}
    {{ include("includes/_breadcrumb.html.twig", {'page': 'iln_langs'}) }}
    <table class="table">
        <tr>
            <th>Code langue</th>
            <th>Nom</th>
            <th>Notices disponibles</th>
        </tr>
        {% for lang in langs %}
            <tr>
                <td>{{ lang.code }}</td>
                <td>{{ lang.langlabel }}</td>
                <td>
                    <a href="{{ url("view_record_lang", {ilnCode: iln.code, ilnSecret: iln.secret, lang: lang.code}) }}">{{ lang.nb }}</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/iln/reprises.html.twig
{% extends "includes/base.html.twig" %}
{% block header %}
{% endblock %}

{% block body %}
    {{ include("includes/_breadcrumb.html.twig", {'page': 'iln_reprises'}) }}
    <p>Page à venir, pour le moment voir les reprises par RCR.</p>
{% endblock %}

templates/iln/search_ppn.html.twig
{{ form_start(form) }}
<div class="row">
<div class="col-md-4">
    {{ form_widget(form.ppn) }}
</div>
<div class="col-md-2">
{{ form_widget(form.submit) }}
</div>
</div>
{{ form_end(form) }}